---
about:
  template: jolla
  id: about-block
---

```{=html}
<div  style="margin: 30px; text-align: center;">
<a class="btn btn-primary" href="https://docs.google.com/document/d/1Qh6eApAK56fcYF1HWEApu5hqM-Kp5ITB3jv8_ilWetc/edit?usp=share_linkf" role="button" target="_blank" style="padding: 15px 30px;">Current CV</a>
</div>
```
# Experiences

::: {#about-block} 
## Case Comprehensive Cancer Center

I am a graduate intern at the Case Comprehensive Cancer Center, where I work on the Cleveland African American Prostate Cancer Project. I love my work and I enjoy being able to interact with Cleveland's community and learn about their healthcare needs. My part in the project involves walking our Project particpants through the prostate cancer screening process, data entry and analysis with the responses we get, and helping out during lay-health advisor screening sessions.
:::

::: {#about-block} 
## Undergradate Research Assistant

I was an undergraduate reseach assistant for Dr. Angela Dixon. In this lab, I learned a lot about neurobiology while working with Manduca sexta moths and measuring their antennal responses through an electroantennogram setup. The experience taught me how to write my own protocols for such materials and I learned how to plan and execute experiments on my own. :::
:::

::: {#about-block} 
## Undergraduate Research Associate

I worked on a project for Dr. Darin Croft, where I inspected ancient fossils from the early Miocene site in Chucal. My work involved examining several tiny fossil teeth in order to determine what species the specimens I had were. Through my work, I learned a lot about paleobiology, ecology, and evolution. I was also able to hone my attention to detail skills as well as learn how to work with expensive and advanced technology in order to photograph my specimens

:::
